---
hostname: rtr-branch1

interfaces:
  - name: GigabitEthernet1
    ipv4:
    - address: 192.168.1.1/24

interface_state:
  - name: GigabitEthernet1
    description: Connection to OSPF neighbor
    enabled: true

ospf_interfaces:
  - name: GigabitEthernet1
    address_family:
      - afi: ipv4
        process:
          id: 100
          area_id: 0