---
hostname: rtr_branch2

interfaces:
  - name: GigabitEthernet1
    ipv4:
    - address: 192.168.2.1/24
  - name: Loopback1
    ipv4:
    - address: 1.1.1.2/32

interface_state:
  - name: GigabitEthernet1
    description: Connection to OSPF neighbor
    enabled: False

ospf_interfaces:
  - name: GigabitEthernet1
    address_family:
      - afi: ipv4
        process:
          id: 100
          area_id: 0