---
- name: configure base environment for CML
  hosts: routers
  gather_facts: false
  # vars:
  #   ansible_password: admin

  tasks:
    - name: configure hostname
      cisco.ios.ios_hostname:
        config:
          hostname: "{{ hostname }}"

    - name: configure interfaces
      cisco.ios.ios_l3_interfaces:
        config: "{{ interfaces }}"

    - name: configure interface state
      cisco.ios.ios_interfaces:
        config: "{{ interface_state }}"

    - name: configure ospf
      cisco.ios.ios_ospfv2:
        config: 
          processes:
          - process_id: "{{ ospf['processes']['process_id'] }}"
            router_id: "{{ item['ipv4'][0]['address'] | ansible.utils.ipaddr('address') | string }}"
      loop: "{{ hostvars[inventory_hostname]['interfaces'] }}"
      when: item['name'] == 'Loopback1'

    - name: configure ospf interfaces
      cisco.ios.ios_ospf_interfaces:
        config: "{{ ospf_interfaces }}"
      
    - name: Configure SNMP
      cisco.ios.ios_snmp_server:
        config: "{{ snmp }}"
