---
- name: test ospf in CML
  hosts: routers
  gather_facts: false
  vars:
    int: {}

  tasks:
    - name: validate interfaces
      ansible.utils.cli_parse:
        command: show ip interface brief
        parser:
          name: ansible.netcommon.pyats
        set_fact: iosxe_show_interface

    - name: combine
      set_fact:
        hostname_interface_data: "{{ int | combine({inventory_hostname: iosxe_show_interface.interface }) }}"

    - name: data
      set_fact:
        int: "{{ int | combine(item) }}"
      loop: >-
        {{
          groups['routers']
          | map("extract", hostvars)
          | map(attribute="hostname_interface_data")
          | list
          }}
      run_once: True

    - name: print dict?
      debug:
        var: int
      run_once: True

    - name: make document
      ansible.builtin.template:
        src: templates/rtr-int-report.j2
        dest: documentation/rtr-int-report.md
      run_once: True