---
- name: test ospf in CML
  hosts: routers
  gather_facts: false
  vars:
    interface_data: {}

  tasks:
    - name: validate interfaces
      ansible.utils.cli_parse:
        command: show ip interface brief
        parser:
          name: ansible.netcommon.pyats
        set_fact: iosxe_show_interface

    - name: combine
      set_fact:
        hostname_interface_data: "{{ interface_data | combine({inventory_hostname: iosxe_show_interface.interface }) }}"

    - name: data
      set_fact:
        interface_data: "{{ interface_data | combine(item) }}"
      loop: >-
        {{
          groups['routers']
          | map("extract", hostvars)
          | map(attribute="hostname_interface_data")
          | list
          }}
      run_once: True

    - name: set dictionary as stats for use in workflow
      set_stats:
        data:
          interface_data: "{{ interface_data }}"

