---
- name: update servicenow incident
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Change state of the incident
      servicenow.itsm.incident:
        number: INC0010005
        attachments:
         - path: "{{ attachment_path }}"
           #path: router-ospf.md
           type: text/markdown
        state: in_progress
        other:
          comments: attached router ospf report

