---
- name: update service now incident
  hosts: localhost
  gather_facts: True
  tasks:
    - name: make router health report
      ansible.builtin.template:
        src: templates/rtr-health-html.j2
        dest: documentation/rtr-health-report.html
      run_once: True
  
    - name: Change state of the incident
      servicenow.itsm.incident:
        number: INC0010035
        # attachments:
        #  - path: documentation/2017Cybersecurity.pdf
        #    # type: text/markdown
        state: in_progress
        other:
          work_notes: "{{ lookup('file', 'documentation/rtr-health-report.html') }}"
      run_once: True

