---
- name: update servicenow incident
  hosts: localhost
  gather_facts: True

  tasks:
    - name: generate timestamp
      ansible.builtin.set_fact:
        current_date: "{{ hostvars['localhost']['ansible_date_time']['date'] }}"

    - name: make router health report in markdown
      ansible.builtin.template:
        src: templates/rtr-health-report.j2
        dest: documentation/rtr-health-report.md
      run_once: True

    - name: make router health report in html
      ansible.builtin.template:
        src: templates/rtr-health-html.j2
        dest: documentation/rtr-health-html.html
      run_once: True
  
    - name: Change state of the incident
      servicenow.itsm.incident:
        number: "{{ incident_id }}"
        attachments:
         - path: documentation/rtr-health-report.md
           type: text/markdown
        state: in_progress
        other:
          work_notes: "{{ lookup('file', 'documentation/rtr-health-html.html') }}"
