---
- name: update servicenow incident
  hosts: localhost
  gather_facts: false

  tasks:
    - name: make router health report
      ansible.builtin.template:
        src: templates/rtr-health-report.j2
        dest: documentation/rtr-health-report.md
      run_once: True
  
    - name: Change state of the incident
      servicenow.itsm.incident:
        number: "{{ incident_id }}"
        attachments:
         - path: documentation/rtr-health-report.md
           #path: router-ospf.md
           type: text/markdown
        state: in_progress
        other:
          comments: attached router health report

